[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "simplex"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.9",
    "numpy",
    "scipy",
]

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
