name = "Simplex"
uuid = "8e87e5a9-4b31-4c7f-8e87-e5a94b314c7f"
authors = ["Guilherme Machado <gui@gmachado.dev>"]
version = "1.0.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-358e-b080-7041a6cba481"

[targets]
test = ["Test"]
